### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by EugenMayer** [morawskim/guzzle-xdebug-middleware#1]
Really nice little addition, very helpful. Not sure why it is not getting any attention, but any reason you did not publish it on https://packagist.org/ ?

Thank you for your work!

**Comment by morawskim** [comment]
I don't publish this package on https://packagist.org/, because I never thinked is ready. Maybe it is the good time. 
I will check at this week compatibility with PSR7 and latest version of Guzzle.

**Comment by EugenMayer** [comment]
latest guzzle i can already confirm, have this running, works great (6.x)

**Comment by morawskim** [comment]
I published this package on packagist.
To add this package to existing project you can use
`composer require mmo/guzzle-xdebug-middleware`

**Comment by EugenMayer** [comment]
Great news, thank you!
