### ISSUE TITLE
XDEBUG_SESSION_START?

### ISSUE THREAD

**Issue by derickr** [morawskim/guzzle-xdebug-middleware#2]
Hi!

I came across this middleware by searching for `XDEBUG_SESSION_START` on GitHub. I'm working on Xdebug 3 and trying to figure out whether I can remove this environment variable. I noticed that you use it in this repository, but I think it would be better to use `XDEBUG_SESSION` instead as the middleware attaches it to *every* request. `XDEBUG_SESSION_START` is meant to signal to Xdebug to do the cooking management itself, which I don't think is what you were intending to do here.

cheers,
Derick

**Comment by morawskim** [comment]
thanks for reporting and explanation
